imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyAppUserBundle/Resources/config/services.yml" }
    - { resource: "@MessageBundle/Resources/config/services.yml" }
    - { resource: "@ChatBundle/Resources/config/services.yml" }
    - { resource: "@ProprieteBundle/Resources/config/services.yml" }
    - { resource: "@ReclamationBundle/Resources/config/services.yml" }
    - { resource: "@evaluationBundle/Resources/config/services.yml" }
    - { resource: "@MyAppMailBundle/Resources/config/services.yml" }
    - { resource: "@HostExperienceBundle/Resources/config/services.yml" }
    - { resource: "@MyAppAhmedBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    image_directory: '%kernel.root_dir%/../web/img/propriete'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

## Swiftmailer Configuration
##swiftmailer:
  ##  transport: "%mailer_transport%"
  ##  host:      "%mailer_host%"
   ## username:  "%mailer_user%"
   ## password:  "%mailer_password%"
   ## spool:     { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: MyApp\UserBundle\Entity\User
    from_email:
            address: you@example.com
            sender_name: You

vich_uploader:
    db_driver: orm
    mappings:
           product_image:
                       uri_prefix:         /images/products
                       upload_destination: '%kernel.root_dir%/../web/images/products'
                       namer:  vich_uploader.namer_hash
                       inject_on_load:     false
                       delete_on_update:   true
                       delete_on_remove:   true
# knpPaginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

hwi_oauth:
    http_client:
        verify_peer: false
    connect:
        confirmation: true
        registration_form: fos_user.registration.form.factory
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookID
            google: googleID
    resource_owners:
        # Facebook Access
        facebook:
            type:                facebook
            client_id:           408069056221595
            client_secret:       9301e5129a1bd0e0b74b5ce21f0107df
            scope:               "email"

nomaya_social:
    buttons:
        facebook:
            url:            "http://www.tourismtunisia.com/"
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      false
            layout:         "button_count"
        twitter:
            url:            null
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            "L'Equipe cartedevisitevirtuelle.fr"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    links:
        facebook:           "http://www.facebook.com/yann.chauvel"
        googleplus:         "https://plus.google.com/105931415830389032796"
    theme:                  'default' # optional

re_captcha:
    public_key: 6Ldm5RsUAAAAALIAEVBvZPPUdvUwlLPBe7pKWGaC
    private_key: 6Ldm5RsUAAAAAAhSFBKJ6pLSOLBqsvF1AIXCM-Pd
    locale: localhost